# Generated by Django 5.1.6 on 2025-02-17 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='servico',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
