# Generated by Django 5.1.6 on 2025-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_horario_data_marcada_horario_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='servicos',
            field=models.ManyToManyField(related_name='servico', to='cadastros.servico'),
        ),
    ]
