# Generated by Django 5.1.6 on 2025-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_horario_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
