# Generated by Django 5.1.6 on 2025-02-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_horario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='usuario',
        ),
    ]
